version: '3.8'

services:
  mongo:
    image: "mongo:6.0"
    container_name: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: avocado_db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  app:
    build: .
    container_name: avocado_api
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/avocado_db?retryWrites=true&w=majority"
    depends_on:
      - mongo
