# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "avocadoVM"
  config.vm.boot_timeout = 900
  config.vm.box = "generic/ubuntu2010"
  
  config.vm.network "forwarded_port", guest: 3389, host: 3389

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.vmx['memsize'] = "2048"
    vmware.vmx['numvcpus'] = "2"
  end

  # Install Ansible using a shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt-get install -y python3-apt 
    sudo apt-get install -y python3-pip
    sudo apt-get install -y ansible firefox ubuntu-desktop
    sudo apt-get install -y xrdp
    sudo systemctl enable xrdp
    sudo systemctl start xrdp
    echo "gnome-session" > /home/vagrant/.xsession
    chown vagrant:vagrant /home/vagrant/.xsession

  # Create the provisioning directory
  mkdir -p /vagrant/provisioning

  # Download main.yml from the repository and place it in the provisioning directory
  wget -O /vagrant/provisioning/main.yml https://raw.githubusercontent.com/rudydesplan/dsti-devops/main/iac/playbooks/main.yml
SHELL
  
  # Use Ansible provisioner to run the main playbook
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provisioning/main.yml"
    ansible.compatibility_mode = "auto"
  end
end
