name: avocado_aci

on:
  push:
    branches:
      - deploy/aci
  pull_request:
    branches:
      - deploy/aci
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: dsti
    AZURE_CONTAINER_REGISTRY: avocadocontainerregistry
    CONTAINER_NAME: avocadocontainer
    DOCKER_COMPOSE_FILE: ./docker-compose.yml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Login to ACR
              run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.5.0
            - name: Cache Docker layers
              uses: actions/cache@v2.1.8
              with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-${{ github.sha }}
                restore-keys: |
                  ${{ runner.os }}-buildx-
            - name: Build and push Docker image
              uses: docker/build-push-action@v4.0.0
              with:
                context: ./flask-api
                file: ./flask-api/Dockerfile
                push: true
                tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache
    deploy_aci:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Login to ACR
              run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
            - name: Deploy to ACI
              run: |
                docker context create avocado_composecontext
                docker context ls
                docker context use avocado_composecontext
                docker compose --file ${{ env.DOCKER_COMPOSE_FILE }} --project-name avocado-api up --detach
            - name: Check ACI deployment status
              run: |
                docker compose --file ${{ env.DOCKER_COMPOSE_FILE }} --project-name avocado-api ps
