name: avocado deploy
on:
  workflow_run:
    workflows:
      - avocado build
    types:
      - completed
env:
    ACR_RESOURCE_GROUP: dsti
    AZURE_CONTAINER_REGISTRY: dsticontainerregistry
    CLUSTER_NAME: dsti-devops
    CLUSTER_RESOURCE_GROUP: dsti
    CONTAINER_NAME: dstidevopscontainer
    DEPLOYMENT_MANIFEST_PATH: |
        ./avocado-api.yaml
jobs:
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v3.5.2
            - uses: azure/login@v1
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/use-kubelogin@v1
              name: Set up kubelogin for non-interactive login
              with:
                kubelogin-version: v0.0.25
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
                use-kubelogin: "true"
            - name: Update manifest with image tag
              run: sed -i 's|dsticontainerregistry.azurecr.io/dstidevopscontainer:<IMAGE_TAG>|${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}|' ${{ env.DEPLOYMENT_MANIFEST_PATH }}
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: avocado
