name: Flask API Test

on:
  push:
    branches: [ dev-mohamed, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      working-directory: ./flask-api
      run: pip install -r requirements.txt

    - name: Start Flask API
      working-directory: ./flask-api
      env:
        PYTHONPATH: "${PYTHONPATH}:/modules"
      run: python service/service.py &
      # The '&' character runs the command in the background so the script can continue.

    - name: Wait for API to start up
      run: sleep 5

    - name: Run tests
      working-directory: ./flask-api
      run: pytest tests/
