name: Flask API Test

on:
  push:
    branches: [ dev-rudy, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0-alpha.7'

    - name: Install dependencies
      working-directory: ./flask-api
      run: pip install --no-cache-dir -r requirements.txt && python setup.py install

    - name: Start Flask API
      working-directory: ./flask-api
      run: python service/service.py &

    - name: Wait for API to start up
      run: sleep 5

    - name: Run tests
      working-directory: ./flask-api
      run: pytest tests/
