name: Flask API Test

on:
  push:
    branches: [ dev-rudy, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: avocado_db
          MONGO_INITDB_ROOT_USERNAME: dsti-devops
          MONGO_INITDB_ROOT_PASSWORD: dsti-devops

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0-alpha.7'

    - name: Install dependencies
      working-directory: ./flask-api
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt && python setup.py install

    - name: Start Flask API
      working-directory: ./flask-api
      env:
        MONGODB_URI: "mongodb://dsti-devops:dsti-devops@localhost:27017/avocado_db?retryWrites=true&w=majority"
      run: python service/service.py &

    - name: Wait for API to start up
      run: sleep 5

    - name: Run tests
      working-directory: ./flask-api
      run: pytest tests/
